name: Bug Report
description: Report a bug or issue with OneStopShop
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix the issue.

  - type: dropdown
    id: wow-version
    attributes:
      label: WoW Version
      description: Which version of WoW Classic are you playing?
      options:
        - Classic Era (Vanilla)
        - Season of Discovery
        - Hardcore
        - Classic Anniversary
        - Cataclysm Classic
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Addon Version
      description: Which version of OneStopShop are you using? (Check /oss or the TOC file)
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: class
    attributes:
      label: Character Class
      description: What class is your character?
      placeholder: "Mage / Warlock"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open the addon window with /oss
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: If you received a Lua error, paste it here. Use /console scriptErrors 1 to enable error display.
      render: text

  - type: textarea
    id: other-addons
    attributes:
      label: Other Addons
      description: List any other addons you're using that might conflict (optional)
